app-config:
  nome: Pedidos-api
  versao: @project.version@

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:pedidos-api
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
      javax:
        persistence:
          validation:
            mode: none
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest